# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44e5a0bcdd23d83d0b2088748810d52f90a20c98d0f5cf04f6693673c3bc456474a736aaae97205a042c1358fdfc6f6ed4b0f9818e9c36f7600b34958362a731

test:
  secret_key_base: 0c6295926fae98a3b65ae025b3f5b8e9d61655defc8fb031e3223dd499067b3cb998e75dd60a752c5d7812c0346d44c95e029212d4d5e0bb1bc6db9ce98e32f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
